name: Kernel Build

on:
  workflow_dispatch:
    inputs:
      toolchain:
          description: 'Write toolchain name gcc/clang'
          required: true
      pushto:
          description: 'Send kernel file to github/telegram'
          required: true
env:
  COMP: ${{ github.event.inputs.toolchain }}
  SEND_TO: ${{ github.event.inputs.pushto }}
  TELEGRAM_TOKEN: ${{ secrets.TG_TOKEN }}
  TELEGRAM_CHAT: ${{ secrets.TG_CHAT }}
  VER: ${{ secrets.K_NAME }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/neutron-projects/docker-image:arch-neutron
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Start building kernel
        run: |
             git config --global --add safe.directory /__w/kernel-build/kernel-build
             git clone https://github.com/Eagle-Projekt/kernel_xiaomi_mt6768 kernel
             cp -af merlin/build.sh kernel/ && cd kernel && chmod +x build.sh
             git config --global user.name "Tanmsyffa"
             git config --global user.email "sltnmsyffaa@gmail.com"
             echo "https://Tanmsyffa:$GH_TOKEN@github.com" > ../.pwd
             git config --global credential.helper "store --file ../.pwd"
             ./build.sh
